language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.0
    - android-24
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-24

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
#    - sys-img-armeabi-v7a-android-24
#    - sys-img-x86-android-17